### PR TITLE
update patch for sidekiq 7.0 support

### PR DESCRIPTION
**Pull request by pconnelly-nuance**
Remove dependency on job_hash_context method to enable upgrade to Sidekiq 7+

### CODE REVIEW

**Review by gschmidt-msft — DISMISSED** [review]
Nice work! Just curious, can you provide an example for context of how this gets applied?

**Comment by pconnelly-nuance** [comment]
> Nice work! Just curious, can you provide an example for context of how this gets applied?

You mean in what case this kind of surrogation would happen? I'm not really sure to be honest. For the most part, the arguments to a job should be minimal and something like an ID which should not be substituted.

**Comment by gschmidt-msft** [comment]
> > Nice work! Just curious, can you provide an example for context of how this gets applied?
> 
> You mean in what case this kind of surrogation would happen? I'm not really sure to be honest. For the most part, the arguments to a job should be minimal and something like an ID which should not be substituted.

Sounds good. Although I guess what I'm missing is just a context for how this situation arises. I haven't dug through the code much, but I imagine there was a use case at some point. Not sure how we'd test this other than making sure it's syntactically correct.

@yelvert , any thoughts on how this gets called? We miss you man!

**Comment by pconnelly-nuance** [comment]
> > > Nice work! Just curious, can you provide an example for context of how this gets applied?
> > 
> > 
> > You mean in what case this kind of surrogation would happen? I'm not really sure to be honest. For the most part, the arguments to a job should be minimal and something like an ID which should not be substituted.
> 
> Sounds good. Although I guess what I'm missing is just a context for how this situation arises. I haven't dug through the code much, but I imagine there was a use case at some point. Not sure how we'd test this other than making sure it's syntactically correct.
> 
> @yelvert , any thoughts on how this gets called? We miss you man!

The way I tested this was to temporarily set a property as a surrogate and run the job. I did that with record_id surrogated, ran the IndexerJob, and got this output:
{"retry"=>true, "queue"=>"high", "lock"=>"until_executed", "on_conflict"=>"log", "args"=>["index", "Facility", 34638, {}], "class"=>"IndexerJob", "jid"=>"7a89aa03689ae757b10f0ba8", "created_at"=>1711642735.9240835, "lock_timeout"=>0, "lock_ttl"=>86400, "lock_prefix"=>"uniquejobs", "lock_args"=>["index", "Facility", 34638, {}], "lock_digest"=>"uniquejobs:3190094e70a9aa16823b5e6ccbbbb168", "enqueued_at"=>1711642735.947443}
{:operation=>"index", :klass=>"Facility", :record_id=>"SUR-20ae2b0c-371c-4919-b1fb-86b1e8f81cd0", :options=>{}}
[2024-03-28T16:18:56.694Z] [Sidekiq] [pid=13515] [tid=1jkr] [severity=INFO] [jid=7a89aa03689ae757b10f0ba8] [worker=IndexerJob] Performing IndexerJob. Duration since enqueued_at: 0.747388 sec
[2024-03-28T16:18:56.957Z] [Sidekiq] [pid=13515] [tid=1jkr] [severity=INFO] done

I also saw this in the log:
[Sidekiq] [queue=default] [jid=c127db3cfe9da4f4d7774d9b] [worker=PatientInterface] PatientInterface.perform Received JSON: {"api_key":"SUR-67ef9958-fc52-48cb-94ae-1d43639b1a2d","first_name":"SUR-93561f70-aef0-4592-a38a-ec7e36028fe4","last_name":"SUR-06c0cef9-9d4d-4713-82ee-04180e026bbc","middle_name":"","sex":"SUR-8217b52e-4214-44a3-a340-9c157dc3d01c","date_of_birth":"SUR-bfe9cbb6-c282-48c2-83c1-2dfcbf4cbb66","patient_type":"OP","message_type":"ADT-A05","patient_id":"SUR-393c414a-6c91-46de-8532-cf164e8e517a","room_number":"","attending_physician":"SUR-f2d43550-4d25-4d71-bc4a-44e0bf3b6c59","attending_physician_number":"SUR-b2ceef1b-a169-4d7f-abdd-7d2b7c84d8eb","admitting_physician":"SUR-f1b22eec-fbfe-4707-a593-7b940d16fe86","admitting_physician_number":"SUR-b2ceef1b-a169-4d7f-abdd-7d2b7c84d8eb","primary_care_physician":"","primary_care_physician_number":"","referring_physician":"","referring_physician_number":"","consulting_physician":"","consulting_physician_number":"","bed":"","admit_date":"SUR-4391ddef-c283-40c9-a4ee-91582ab56573","discharged_at":"","scheduling_information":"","scheduled_id":"","mrn_number":"SUR-9f1f9a01-78ac-439f-bb1c-531d5ba9e71d","uuid":"fa5774a1-623b-4514-975e-c0bf3f429d2d","consulting_doctor_number":""}

**Review by gschmidt-msft — DISMISSED** [review]

**Review by gschmidt-msft — APPROVED** [review]

**Pull request merged**
